# Snapcraft Recipe for whisper.cpp
# Copyright 2025 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: MIT
name: whisper-cpp
title: whisper.cpp (UNOFFICIAL)
summary: Port of OpenAI's Whisper model in C/C++
description: |-
  **Distribution-specific information**

  This is NOT an official distribution of whisper.cpp, please file any issue
  regarding the usage of this snap to the snap's own issue tracker:

      Issues · 林博仁 Buo-ren Lin / Unofficial snap packaging for whisper.cpp · GitLab
      https://gitlab.com/brlin/whisper.cpp-snap/-/issues

  Refer to the upstream project website for more info about this application:

      ggerganov/whisper.cpp: Port of OpenAI's Whisper model in C/C++
      https://github.com/ggerganov/whisper.cpp

  The following commands are provided by this snap:

  * `whisper-cpp.cli`: Corresponds to the `whisper-cli` command, which is the main CLI interface for whisper.cpp.
  * `whisper-cpp.download-ggml-model`: Upstream utility script to download GGML models for whisper.cpp.
  * `whisper-cpp.download-vad-model`: Upstream utility script to download VAD models for whisper.cpp.

  You may run the following command in a terminal to setup the upstream preferred `whisper-cli` command:

      sudo snap alias whisper-cpp.cli whisper-cli

  This snap DOES NOT support GPU acceleration yet, it is currently build against the x86_64 baseline ABI for greatest compatibility.

  **Upstream information(some features are not applicable to snap)**

  High-performance inference of [OpenAI's Whisper](https://github.com/openai/whisper) automatic speech recognition (ASR) model:

  * Plain C/C++ implementation without dependencies
  * Apple Silicon first-class citizen - optimized via ARM NEON, Accelerate framework, Metal and [Core ML](https://github.com/ggerganov/whisper.cpp#core-ml-support)
  * AVX intrinsics support for x86 architectures
  * VSX intrinsics support for POWER architectures
  * Mixed F16 / F32 precision
  * [4-bit and 5-bit integer quantization support](https://github.com/ggerganov/whisper.cpp#quantization)
  * Zero memory allocations at runtime
  * Support for CPU-only inference
  * [Efficient GPU support for NVIDIA](https://github.com/ggerganov/whisper.cpp#nvidia-gpu-support-via-cublas)
  * [OpenVINO Support](https://github.com/ggerganov/whisper.cpp#openvino-support)
  * [C-style API](https://github.com/ggerganov/whisper.cpp/blob/master/whisper.h)
icon: snap/gui/placeholder-icon.png
license: MIT
contact: https://gitlab.com/brlin/whisper.cpp-snap/-/issues
issues: https://gitlab.com/brlin/whisper.cpp-snap/-/issues
source-code: https://gitlab.com/brlin/whisper.cpp-snap
website: https://gitlab.com/brlin/whisper.cpp-snap

base: core24
adopt-info: main
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  riscv64:

parts:
  main:
    source: https://github.com/ggerganov/whisper.cpp.git
    plugin: cmake
    cmake-parameters:
      # Make installation paths relative to the snap prefix
      - -DCMAKE_INSTALL_PREFIX=""
      - -DCMAKE_BINARY_DIR="${CRAFT_PART_INSTALL}"

      # The server example will fail if enabled
      - -DWHISPER_FFMPEG=OFF

      # This snap is meant for the baseline x86_64 ABI for greatest
      # compatibility
      - -DGGML_NATIVE=OFF
      - -DGGML_AVX=OFF
      - -DGGML_AVX2=OFF
      - -DGGML_AVX512=OFF
      - -DGGML_AVX512_VBMI=OFF
      - -DGGML_AVX512_VNNI=OFF
      - -DGGML_F16C=OFF
      - -DGGML_FMA=OFF

      # Support GPU acceleration via the Vulkan API
      - -DGGML_VULKAN=ON

      # Build artifact caching is not applicable in snap packaging
      - -DGGML_CCACHE=OFF

      # Support media file conversion
      - -DWHISPER_FFMPEG=ON
    build-snaps:
      - ffmpeg-2404-sdk
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PATH: /snap/ffmpeg-2404-sdk/current/usr/bin${PATH:+:$PATH}
    build-packages:
      - glslc
      - pkg-config
      - libcairo2-dev
      - libmpg123-dev
      - libogg-dev
      - libopenjp2-7-dev
      - libopus-dev
      - librsvg2-dev
      - libspeex-dev
      - libtheora-dev
      - libtwolame-dev
      - libva-dev
      - libvdpau-dev
      - libvpx-dev
      - libvulkan-dev
      - libwebp-dev

      # selective-checkout dependencies
      - curl
      - jq
      - sed
      - git
    stage-packages:
      # For download scripts, bash is not needed as it is available in the base snap
      - curl

      - libcairo2
      - libgomp1
      - libmpg123-0t64
      - libogg0
      - libopenjp2-7
      - libopus0
      - librsvg2-2
      - libspeex1
      - libtheora0
      - libtwolame0
      - libva2
      - libva-drm2
      - libva-x11-2
      - libvdpau1
      - libvpx9
      - libvulkan1
      - libwebp7
      - libwebpmux3
    override-pull: |
      set -o nounset

      if ! craftctl default; then
          printf \
              'Error: Unable to run the default action of this step.\n' \
              1>&2
          exit 2
      fi

      project_dir="${CRAFT_PROJECT_DIR:-"${SNAPCRAFT_PROJECT_DIR}"}"
      selective_checkout_opts=(
          --append-packaging-revision
      )
      if ! "${project_dir}/snap/local/scriptlets/selective-checkout" "${selective_checkout_opts[@]}"; then
          printf \
              'Error: Unable to run the selective-checkout scriptlet.\n' \
              1>&2
          exit 2
      fi
    override-build: "${CRAFT_PROJECT_DIR}/snap/local/scriptlets/main-override-build"
    prime:
      # Development files
      - -include

      # Unneeded binaries
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicui18n.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicuio.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutu.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtheora.so*

  gpu-2404:
    after:
      - main
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
      - bin/gpu-2404-wrapper

layout:
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

apps:
  cli:
    command: bin/whisper-cli
    command-chain:
      - bin/gpu-2404-wrapper
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      # /usr/bin provides the "snapctl" command for the gpu-2404-wrapper launcher
      PATH: $SNAP/ffmpeg-platform/usr/bin:/usr/bin
    plugs:
      # For accessing models
      - home
      - removable-media

      # For accessing GPU resources
      - opengl

  download-ggml-model:
    command: bin/download-ggml-model.sh
    plugs: &download-scripts-plugs
      # For storing models
      - home
      - removable-media

      # For downloading models
      - network

  download-vad-model:
    command: bin/download-vad-model.sh
    plugs: *download-scripts-plugs
